name: qnect_quiz_crafter
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  connectivity_plus: ^7.0.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.4
  loading_animation_widget: ^1.3.0
  equatable: ^2.0.7
  intl: ^0.20.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0
  fl_chart: ^0.63.0
  percent_indicator: ^4.2.5
  lucide_icons: ^0.257.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.8
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  lottie: ^3.1.2
  just_audio: ^0.9.39
  encrypt: ^5.0.1
  file_picker: ^10.3.7
  record: ^6.1.2
  permission_handler: ^12.0.1
  audioplayers: ^6.0.0
  flutter_sslcommerz: ^3.0.1
  screen_protector: ^1.4.10
  flutter_native_splash: ^2.4.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/core/app_primary_logo.png"
  adaptive_icon_background: "#015055"
  adaptive_icon_foreground: "assets/core/app_primary_logo.png"





flutter:


  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/admin/
    - assets/images/certificates/
    - assets/images/company/
    - assets/images/dummy_user_avatar/
    - assets/badges/
    - assets/icons/
    - assets/trophy/
    - assets/sounds/swipe.mp3
    - assets/animations/
    - assets/core/
    - .env


  fonts:
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Regular.ttf
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Bold.ttf
          weight: 700

    - family: Aboreto
      fonts:
        - asset: assets/fonts/Aboreto/Aboreto-Regular.ttf
